flake.lock, proof-producer/README.md, proof-producer/bin/proof-producer/include/nil/proof-generator/arg_parser.hpp, proof-producer/bin/proof-producer/include/nil/proof-generator/prover.hpp, proof-producer/bin/proof-producer/src/arg_parser.cpp, proof-producer/bin/proof-producer/src/main.cpp
This PR adds final stage to proof-producer
closes #28
=> Add merge-proofs stage to proof-producer

proof-producer/CMakeLists.txt, proof-producer/bin/proof-producer/CMakeLists.txt, proof-producer/bin/proof-producer/include/nil/proof-generator/prover.hpp, proof-producer/libs/output_artifacts/CMakeLists.txt, proof-producer/libs/output_artifacts/include/nil/proof-generator/assignment_table_writer.hpp
Took an implementation from [write_assignments.hpp](https://github.com/NilFoundation/placeholder/blob/feature/proof-prioducer-assignment-table-writer/zkevm-framework/libs/assigner_runner/include/zkevm_framework/assigner_runner/write_assignments.hpp/#L91) 
Simplified it a bit, added usage of table description and unified template alias declarations
Checked with circuits and tables from the CI, saved tables are the same as provided
=> proof-producer: add assignment table writer

.github/workflows/check-proof-producer.yml
The difference between successful runs and the failed runs is that failed ones contain
./transpiler_output_* folders, that shall only appear as a result of the check-proof-producer step.
=> make CI more robust

crypto3/libs/zk/include/nil/crypto3/zk/snark/systems/plonk/placeholder/preprocessor.hpp, parallel-crypto3/libs/parallel-zk/include/nil/crypto3/zk/snark/systems/plonk/placeholder/preprocessor.hpp
found local variable of `cycle_representation`  type that is currently required only for calculating `sigma_perm_polys` vector, but its lifetime is prolonged till the method end which adds about 15% (~4GB on sha256 example) to peak memory consumption
```
->09.28% (2,566,914,048B)
->04.64% (1,283,457,024B)
``` 
before: `peak cost: "25.1 GiB" heap "621.3 MiB" heap extra "0 B" stacks`
after: `peak cost: "21.6 GiB" heap "9.3 MiB" heap extra "0 B" stacks`
=> preprocessor: optimize memory usage

parallel-crypto3/libs/parallel-containers/CMakeLists.txt
Due to invalid test subdirectory adding parallel crypto3 test build leaked into each dependent binary compilation
=> fix redundant parallel-crypto3 test build

.clang-format, .envrc, .gitignore, flake.nix
`.clang-format`: preserve include blocks groups (instead of grouping all the includes and sorting them)
`.envrc`: allow specifying used derivation in environment (mainly so that whoever uses clang could just set `PLACEHOLDER_DEVELOP_DERIVATION` to `.#develop-clang`)
`.gitignore`: add vscode, direnv and cmake related files
`CMakeLists.txt`: enable tests in root too (so it works without `nix develop`)
`flake.nix`: add `develop-clang` derivation
=> Config files improvements

.github/workflows/deb-package-proof-producer-bundler.yaml, .github/workflows/nightly.yml, crypto3/CMakeLists.txt, flake.nix, proof-producer.nix, proof-producer/CMakeLists.txt, proof-producer/bin/proof-producer/CMakeLists.txt, proof-producer/libs/assigner/CMakeLists.txt, proof-producer/libs/output_artifacts/CMakeLists.txt, proof-producer/tests/bin/proof-producer/CMakeLists.txt, proof-producer/tests/libs/output_artifacts/CMakeLists.txt
- Fix protobuf package import to fetch absl dependencies automatically
- Enable building proof-producer binaries as statically linked
- Add bundler to make deb package
- Add package version as a revCount
=> Add deb bundler for proof-producer package

proof-producer/bin/proof-producer/src/main.cpp
Fast generate partial proof combines several stages but lacks intermediate output (assignment table description) that is needed for further stages
=> Save assignment description file on fast partial proof

crypto3/libs/blueprint/include/nil/blueprint/bbf/circuit_builder.hpp, crypto3/libs/blueprint/include/nil/blueprint/bbf/components/hashes/keccak/keccak_dynamic.hpp, crypto3/libs/blueprint/include/nil/blueprint/bbf/components/hashes/keccak/keccak_round.hpp, crypto3/libs/blueprint/include/nil/blueprint/bbf/components/hashes/keccak/util.hpp, crypto3/libs/blueprint/test/CMakeLists.txt, crypto3/libs/blueprint/test/bbf/keccak_dynamic.cpp, crypto3/libs/blueprint/test/bbf/keccak_round.cpp
Keccak component in bbf; closes #147
=> keccak dynamic and round

crypto3/libs/hash/example/CMakeLists.txt, crypto3/libs/hash/example/hashes.cpp, crypto3/libs/hash/include/nil/crypto3/hash/block_to_field_elements_wrapper.hpp, crypto3/libs/hash/test/poseidon.cpp, crypto3/libs/zk/include/nil/crypto3/zk/snark/systems/plonk/placeholder/preprocessor.hpp, crypto3/libs/zk/test/transcript/transcript.cpp, parallel-crypto3/libs/parallel-containers/example/CMakeLists.txt, parallel-crypto3/libs/parallel-zk/test/transcript/transcript.cpp
This PR adds padding option (enabled by default) to `conditional_block_to_field_wrapper`.
closes #273
=> Implemented padding at the stage of block_to_field_wrapper

crypto3/libs/blueprint/test/bbf/keccak_round.cpp, crypto3/libs/blueprint/test/bbf/opcode_poc.cpp, crypto3/libs/blueprint/test/bbf/poseidon.cpp, crypto3/libs/blueprint/test/bbf/tester.cpp
=> Use boost assertions in bbf tests

proof-producer/tests/bin/proof-producer/test_zkevm_bbf_circuits.cpp
accidentally disabled circuits tests during the renaming [here](https://github.com/NilFoundation/placeholder/pull/310) , bringing it back
=> restore accidentally disabled tests

.github/workflows/clang-sanitizers-linux-nix-check.yml, .github/workflows/gcc-linux-nix-check.yml
We experience OOM on GCC build. Limit the cores number to have the build more robust.
=> limit gcc build by 12 cores

proof-producer/bin/proof-producer/include/nil/proof-generator/command_step.hpp, proof-producer/bin/proof-producer/include/nil/proof-generator/commands/agg_challenge_command.hpp, proof-producer/bin/proof-producer/include/nil/proof-generator/commands/aggregated_fri_proof_command.hpp, proof-producer/bin/proof-producer/include/nil/proof-generator/commands/compute_combined_q_command.hpp, proof-producer/bin/proof-producer/include/nil/proof-generator/commands/detail/io/assignment_table_io.hpp, proof-producer/bin/proof-producer/include/nil/proof-generator/commands/detail/io/circuit_io.hpp, proof-producer/bin/proof-producer/include/nil/proof-generator/commands/detail/io/lpc_scheme_io.hpp, proof-producer/bin/proof-producer/include/nil/proof-generator/commands/detail/io/preprocessed_data_io.hpp, proof-producer/bin/proof-producer/include/nil/proof-generator/commands/detail/proof_gen.hpp, proof-producer/bin/proof-producer/include/nil/proof-generator/commands/fill_assignment_command.hpp, proof-producer/bin/proof-producer/include/nil/proof-generator/commands/gen_consistency_check_command.hpp, proof-producer/bin/proof-producer/include/nil/proof-generator/commands/merge_proofs_command.hpp, proof-producer/bin/proof-producer/include/nil/proof-generator/commands/preset_command.hpp, proof-producer/bin/proof-producer/include/nil/proof-generator/commands/verify_command.hpp, proof-producer/bin/proof-producer/include/nil/proof-generator/evm_verifier_print.hpp, proof-producer/bin/proof-producer/include/nil/proof-generator/resources.hpp, proof-producer/libs/assigner/include/nil/proof-generator/assigner/bytecode.hpp, proof-producer/libs/assigner/include/nil/proof-generator/assigner/trace_parser.hpp, proof-producer/tests/bin/proof-producer/test_zkevm_bbf_circuits.cpp
- Added separate OutOfMemory error and mapped it to std::bad_alloc
- Wrapped all IO errors with input/output artifacts operations
- Moved to exceptions in assigner trace parser in order to make a difference between IO errors and malformed or inconsistent traces
- Wrapped all `std::logic_error`  exceptions from crypto3 with ProverError
- Added retcode check to the proof producer tests
=> proof-producer: use proper retcodes

verify-proofs.nix
The list of tests for verification is including the elements, that are not passing verification for now
=> correct the list to match the current implementation status

crypto3/libs/blueprint/include/nil/blueprint/bbf/components/algebra/curves/weierstrass/ec_double.hpp, crypto3/libs/blueprint/include/nil/blueprint/bbf/components/algebra/curves/weierstrass/ec_incomplete_add.hpp, crypto3/libs/blueprint/include/nil/blueprint/bbf/components/algebra/curves/weierstrass/ec_scalar_mult.hpp, crypto3/libs/blueprint/include/nil/blueprint/bbf/components/algebra/curves/weierstrass/ec_two_t_plus_q.hpp, crypto3/libs/blueprint/include/nil/blueprint/bbf/components/algebra/fields/non_native/add_sub_mod_p.hpp, crypto3/libs/blueprint/include/nil/blueprint/bbf/components/algebra/fields/non_native/check_mod_p.hpp, crypto3/libs/blueprint/include/nil/blueprint/bbf/components/algebra/fields/non_native/flexible_multiplication.hpp, crypto3/libs/blueprint/include/nil/blueprint/bbf/components/algebra/fields/non_native/negation_mod_p.hpp, crypto3/libs/blueprint/include/nil/blueprint/bbf/components/detail/carry_on_addition.hpp, crypto3/libs/blueprint/include/nil/blueprint/bbf/components/detail/choice_function.hpp, crypto3/libs/blueprint/include/nil/blueprint/bbf/components/detail/range_check_multi.hpp, crypto3/libs/blueprint/include/nil/blueprint/bbf/components/pubkey/ecdsa/ecdsa_recovery.hpp, crypto3/libs/blueprint/test/CMakeLists.txt, crypto3/libs/blueprint/test/bbf/algebra/curves/weierstrass/ec_full_add.cpp, crypto3/libs/blueprint/test/bbf/algebra/curves/weierstrass/ec_incomplete_add.cpp, crypto3/libs/blueprint/test/bbf/algebra/curves/weierstrass/ec_scalar_mult.cpp, crypto3/libs/blueprint/test/bbf/algebra/curves/weierstrass/ec_two_t_plus_q.cpp, crypto3/libs/blueprint/test/bbf/algebra/fields/non_native/add_sub_mod_p.cpp, crypto3/libs/blueprint/test/bbf/algebra/fields/non_native/check_mod_p.cpp, crypto3/libs/blueprint/test/bbf/algebra/fields/non_native/flexible_multiplication.cpp, crypto3/libs/blueprint/test/bbf/algebra/fields/non_native/negation_mod_p.cpp, crypto3/libs/blueprint/test/bbf/detail/range_check_multi.cpp, crypto3/libs/blueprint/test/bbf/pubkey/ecdsa/ecdsa_recovery.cpp
Migrated 3 new circuits in bbf:
- ec_two_t_plus_q
- ec_scalar_mult
- ecdsa_recovery
Normalizing imports and variables accros subcomponents
=> 175 complete ecdsa bbf

.github/workflows/pull-request.yml, crypto3/libs/blueprint/test/test_plonk_component.hpp, crypto3/libs/math/include/nil/crypto3/math/polynomial/polynomial_dfs.hpp, crypto3/libs/math/test/polynomial_dfs.cpp, crypto3/libs/zk/include/nil/crypto3/zk/commitments/batched_commitment.hpp, crypto3/libs/zk/include/nil/crypto3/zk/commitments/detail/polynomial/eval_storage.hpp, crypto3/libs/zk/include/nil/crypto3/zk/snark/systems/plonk/placeholder/gates_argument.hpp, crypto3/libs/zk/include/nil/crypto3/zk/snark/systems/plonk/placeholder/lookup_argument.hpp, crypto3/libs/zk/include/nil/crypto3/zk/snark/systems/plonk/placeholder/preprocessor.hpp, crypto3/libs/zk/include/nil/crypto3/zk/snark/systems/plonk/placeholder/prover.hpp, crypto3/libs/zk/include/nil/crypto3/zk/snark/systems/plonk/placeholder/verifier.hpp, crypto3/libs/zk/test/systems/plonk/placeholder/placeholder_lookup_argument.cpp, parallel-crypto3/libs/parallel-math/include/nil/crypto3/math/polynomial/polynomial_dfs.hpp, parallel-crypto3/libs/parallel-math/test/polynomial_dfs.cpp, parallel-crypto3/libs/parallel-zk/include/nil/crypto3/zk/commitments/batched_commitment.hpp, parallel-crypto3/libs/parallel-zk/include/nil/crypto3/zk/commitments/detail/polynomial/eval_storage.hpp, parallel-crypto3/libs/parallel-zk/include/nil/crypto3/zk/snark/systems/plonk/placeholder/gates_argument.hpp, parallel-crypto3/libs/parallel-zk/include/nil/crypto3/zk/snark/systems/plonk/placeholder/lookup_argument.hpp, parallel-crypto3/libs/parallel-zk/include/nil/crypto3/zk/snark/systems/plonk/placeholder/preprocessor.hpp, parallel-crypto3/libs/parallel-zk/include/nil/crypto3/zk/snark/systems/plonk/placeholder/prover.hpp, parallel-crypto3/libs/parallel-zk/include/nil/crypto3/zk/snark/systems/plonk/placeholder/verifier.hpp, parallel-crypto3/libs/parallel-zk/test/systems/plonk/placeholder/placeholder_lookup_argument.cpp
This is an implementation of the basic version of LogUp in the lookup argument. It also optimized lookup input calculation.
We should do the same in the permutation argument later, here's a task for that: 
https://www.notion.so/nilfoundation/Implement-logUp-like-structure-in-permutation-argument-and-remove-unnecessary-values-like-lookup_pa-19ec61485260801bb249d2ea9fda05f4
=> 308 implement basic logup algorithm

crypto3/libs/blueprint/include/nil/blueprint/zkevm/zkevm_word.hpp, crypto3/libs/blueprint/include/nil/blueprint/zkevm_bbf/rw_small_field.hpp, crypto3/libs/blueprint/include/nil/blueprint/zkevm_bbf/subcomponents/rw_table_small_field.hpp, crypto3/libs/blueprint/test/zkevm_bbf/hardhat.cpp, crypto3/libs/blueprint/test/zkevm_bbf/rw.cpp
Values separated in 16 bits chunks:
- id
- rw_id
- address
- storage
- value
- value_before
- state_root
- state_root_before
NB: State_root and state_root_before are currently never initialized in rw nor rw_small_field
=> babybear rw circuit

crypto3/libs/blueprint/include/nil/blueprint/zkevm_bbf/opcodes/sar.hpp, crypto3/libs/blueprint/include/nil/blueprint/zkevm_bbf/opcodes/shr.hpp
This PR adds missing constraints to the SHR and SAR circuits.
This prevents a vulnerability spotted by @ayashunsky. It would allow an attacker to use wrong values of $r$, exploiting overflows modulo $$2^{256}$$. More precisely: we were checking the condition $$r\cdot b + q \equiv a \pmod{2^{256}}$$. Given the intended solution $$r$$, set (for example) $$r' = 2^{255} + r$$. This also satisfies the modular equation, for any $$b \equiv 0 \pmod{2}$$ (i.e. for any non-zero shift). 
We prevent this by checking that the multiplication $$r\cdot b$$ does not overflow $$2^{256}$$, which never happens in honest cases.
=> Fix for SHR and SAR

crypto3/libs/blueprint/include/nil/blueprint/zkevm_bbf/opcodes/sar.hpp, crypto3/libs/blueprint/include/nil/blueprint/zkevm_bbf/opcodes/shl.hpp, crypto3/libs/blueprint/include/nil/blueprint/zkevm_bbf/opcodes/shr.hpp, crypto3/libs/blueprint/test/zkevm_bbf/opcodes/byte_ops.cpp
Slightly different from the SAR and SHR opcodes (the SHL circuit is smaller), but still reusing most of the same logic. Also, I made small corrections in previous opcodes:
- fixed an error in a comment in SAR and SHR.
- removed an unnecessary value from SHR (it was a leftover from the SAR code, it was allocated but never constrained).
=> SHL opcode circuit adapted for small fields 
